version: "3"

services:
  nrpimonitor:
    image: ghcr.io/zetroot/nrpimonitor:v0.2.5
    platform: linux/arm64
    restart: always
    ports:
      - 80:80
    container_name: nrpimon
    environment:
      - ConnectionStrings__default=Data Source=/opt/data/app.db
    volumes:
      - ./nrpimondb/:/opt/data/
  
  prometheus:
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/data/prometheus
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    platform: linux/arm64
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/data/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false

    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  prometheus-data:
